### ISSUE TITLE
Transmitting data between javascript and python backend

### ISSUE THREAD

**Issue by CristianGaudino** [TeamTwo2020/bored_games#1]
Transmitting between the two seems to be a bigger issue than previously thought, using POST may be an option though it will lead to longer delays than we would like.

**Comment by michaelSmithUCC** [comment]
POST may lead to longer delays, but i think at this point we should see it as technical debt

**Comment by CristianGaudino** [comment]
There does not seem to be a way to do it without a lot more work

**Comment by michaelSmithUCC** [comment]
Should we change tact then and have it the documentation
