### ISSUE TITLE
Communication problem between Javascript and Python backend.

### ISSUE THREAD

**Issue by paul117430404** [TeamTwo2020/bored_games#2]
Node is not a viable option, POST can't be used effectively either, especially for server to JavaScript communication.

**Comment by CristianGaudino** [comment]
We can't see a practical way of producing the chosen game using the methods we started with, unless we redesign the game we may have to move away from a web app

**Comment by CristianGaudino** [comment]
After much discussion, and consulting Klaas we have decided to scrap our original game idea due to this issue that as of now does not have a viable solution for our time frame.
