### ISSUE TITLE
Issue with movement keys on topdown

### ISSUE THREAD

**Issue by CristianGaudino** [TeamTwo2020/bored_games#4]
Bug occurs when two keys are held together, only one will register while the other does nothing, once one is let go the other will do nothing until repressed

**Comment by michaelSmithUCC** [comment]
i can see the code on the pull request but is there file i can clone and add to the webpage or has adrian pulled the whole lot

**Comment by CristianGaudino** [comment]
Issue resolved by revamping the movement system for collision between objects
